version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.6.0
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      VIRTUAL_PORT: ${UI_PORT}
    ports:
      - "${UI_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
